config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  resources :wikis

  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'modify_privacy' => 'wikis#modify_privacy'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize { self.role ||= :standard}
  after_create :welcome_email

  has_many :collaborators
  has_many :wikis, through: :collaborators

  # Validations for name
  validates :name, presence: true, length: { minimum: 1, maximum: 100 }

  # Validations for password
  validates :password, presence: true, length: { minimum: 8 }

  # Validations for email
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 6, maximum: 254 }

  enum role: [:standard, :premium, :admin]

def avatar_url(size)
  gravatar_id = Digest::MD5::hexdigest(self.email).downcase
  "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?s=#{size}"
end

  private
  def welcome_email
    MyMailer.new_user(self).deliver_now
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new

  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
    @user = user
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
    redirect_to :root
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)

    if @user.save
      flash[:notice] = "Your changes have been saved."
      redirect_to @user
    else
      flash.now[:alert] = "There was an error saving your changes. Please try again."
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:bio, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <%= bootstrap_form_for @user do |f| %>
        <%= f.text_area :bio, autofocus: true, placeholder: "Tell us about yourself!", rows: '8' %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if current_user.premium? || current_user.admin? %>
      <div class="container content">
      	<div class="pricing hover-effect">
      		<div class="pricing-head">
      			<h3>Standard
            <span>Free and open access to Blocipedia</span>
      			</h3>
      			<h4>Free!</h4>
      		</div>
      		<ul class="pricing-content list-unstyled">
      			<li>Create public wikis</li>
      			<li>Edit alongside other Blocipedians</li>
      			<li>Customize your user profile</li>
      			<li>Keep up with the Joneses</li>
      		</ul>
      		<div class="pricing-footer">
      			<p>Tired of paying me an exorbitant sum? Downgrade today!</p>
      			<%= link_to "Downgrade", downgrade_path, class: "btn btn-danger" %>
      		</div>
      	</div>
  		</div>
    <% end %>
    <% if current_user.standard? %>
      <div class="container content">
        <div class="pricing hover-effect">
        	<div class="pricing-head">
        		<h3>Premium
            <span>Privacy and collaboration await!</span>
        		</h3>
        		<h4><i>$</i>14<i>.99</i>
        		<span>Per Month</span>
        		</h4>
        	</div>
        	<ul class="pricing-content list-unstyled">
        		<li>Create private wikis that cannot be seen by standard users</li>
            <li>Invite your friends to share your private pages</li>
        		<li>Premium support from the Blocipedia team</li>
            <li>A free dog!</li>
            <li>Power like unto a god</li>
        	</ul>
          <div class="pricing-footer">
        		<p>Want access to the best of Blocipedia? Upgrade today!</p>
        		<%= link_to "Upgrade", new_charge_path, class: 'btn btn-success' %>
        	</div>
         </div>
    	 </div>
      <% end %>
   </div>
 </div>


<br>
<br>
<center>
<strong>Powered by <a href="http://j.mp/metronictheme" target="_blank">KeenThemes</a></strong>
</center>
<br>
<br>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          Currently a <strong><%= @user.role %></strong> member of Blocipedia.
          <br>
          <br>
          <%= pluralize(@user.wikis.count, 'wiki') %>
        <small>
      </div>
    </div>
  </div>
  <div class="col-md-2">
    <br><br>
    <%= link_to "Profile Settings", edit_user_path, class: "btn btn-success" %>
  </div>
</div>
<br><br>
<div class="row">
  <div class="col-md-8">
    <article class="media">
      <h3 class="media-heading">Email</h3>
      <p class="info"><%= @user.email %></p>

      <br>

      <h3 class="media-heading">Bio</h3>
      <p class="info">Personalize your bio, and tell the Blocpedia community a bit about you!</p>
    </article>
  </div>
</div>