config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  resources :wikis

  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'modify_privacy' => 'wikis#modify_privacy'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  has_many :collaborators
  has_many :users, through: :collaborators
  has_attached_file :image,
    :path => ":rails_root/public/images/:id/:style/:filename",
    :url => "/images/:id/:style/:filename",
    :styles => { medium: "300x300>", thumb: "100x100>" }

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }

  validates :body, presence: true, length: { minimum: 15, maximum: 1000 }

  validates_attachment :image, content_type: { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @user = User.find(@wiki.user_id)
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.image = params[:wiki][:image]
    @wiki.user_id = current_user.id
    @wiki.public = true

    if @wiki.save
      flash[:notice] = "Your wiki has been added to Blocipedia"
      redirect_to @wiki
    else
      flash.now[:alert] = "Your wiki couldn't be saved"
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @user = current_user
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "Your wiki could not be deleted. Please try again."
    end
  end

  def modify_privacy
    @wiki = Wiki.find(params[:id])
    if @wiki.public == true
      @wiki.public = false
    else
      @wiki.public = true
    end

    if @wiki.save
      flash[:notice] = "The privacy status of \"#{@wiki.title}\" was modified."
      redirect_to @wiki
    else
      flash.now[:alert] = "Your wiki's privacy could not be changed. Please try again."
      render :edit
    end
  end

  private
  # expect these 4 attriubtes
    def wiki_params
      params.require(:wiki).permit(:title, :body, :user_id, :public, :image)
    end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <br>
    <p><i>Blocipedia supports Markdown, so have fun and make your wiki stand out!</i></p>
    <%= bootstrap_form_for @wiki do |f| %>
      <%= f.text_field :title, autofocus: true %>
      <%= f.text_area :body, rows: "10" %>
      <%= f.submit "Submit", class: 'btn btn-primary pull-right' %>
      <br>
    <% end %>

    <% if @wiki.public == true && ((@user.premium? && @user.id == @wiki.user_id) || @user.admin?) %>
      <br>
      <p><strong>Would you like to make your wiki private, and shut out the peons?</strong></p>
      <%= link_to "Private Wiki", modify_privacy_path(id: @wiki.id), class: "btn btn-primary pull-right" %>

    <% elsif @wiki.public == false && @user.id == @wiki.user_id %>
      <br>

      <%= form_tag collaborators_path, method: :post do %>
        <%= label_tag 'Choose a collaborator from the list below' %>
        <%= select_tag 'collaborators', options_for_select(User.all.collect{ |u| [u.name, u.id] }), label: "List of possible collaborators", class: "form-control", multiple: true %>
        <br>
        <%= text_field_tag :collaborator, "", class: 'form-control', placeholder: "Enter your choice here", onfocus: "placeholder=''"%>
        <%= hidden_field_tag :wiki_id, @wiki.id %>
        <%= submit_tag "Add Collaborator",  class: 'btn btn-primary pull-right' %>
      <% end %>

      <br>
      <br>
      <p><strong>Would you like to make your wiki public again?</strong></p>
      <%= link_to "Public Wiki", modify_privacy_path(id: @wiki.id), class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Public Wikis</h1>

<br><br>
<div class="row">
  <div class="col-md-8 col-md-offset-1 col-sm-4">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <% unless wiki.image.exists? %>
          <%= link_to wiki do %>
            <%= image_tag("#{wiki.file}", class: 'wiki-image') %>
            <h4 class="wiki-text"><%= "#{wiki.title}" %></h4>
          <% end %>
        <% else %>
          <%= link_to wiki do %>
            <%= image_tag(wiki.image.url, class: 'wiki-image') %>
            <h4 class="wiki-text"><%= "#{wiki.title}" %></h4>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-2 col-sm-2">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wikis</p>
    <ul>
      <li>Don't get offended when edits get made to your content</li>
      <li>Always cite your sources</li>
      <li>Don't forget to include a picture</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= bootstrap_form_for @wiki do |f| %>
      <%= f.text_field :title, autofocus: true %>
      <%= f.text_area :body, rows: "10" %>
      <%= f.file_field :image %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= "#{@wiki.title}"%><small><%=" by #{@user.name}" %></small></h1>

<div class="row">
  <div class="col-md-6">
    <p><%= markdown(@wiki.body) %></p>
    <% if @wiki.collaborators.exists? %>
      <h5><i>Collaborators:</i></h5>
      <%= @wiki.collaborators.each do |c| %>
        <p>
          <%= c.user.name %>
          <% if @wiki.user_id == current_user.id %>
            <%= link_to "", collaborator_path(c.id), method: :delete, class: 'glyphicon glyphicon-remove' %>
          <% end %>
        </p>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-4">
    <% unless @wiki.image.exists? %>
      <%= image_tag("#{@wiki.file}", class: 'wiki-image') %>
    <% else %>
      <%= image_tag(@wiki.image.url, class: 'wiki-image') %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <% if policy(@wiki).update? %>
      <%= link_to "Edit Wiki", edit_wiki_path, class: "btn btn-primary" %>
    <% end %>
    <% if policy(@wiki).delete? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete this Wiki?" } %>
    <% end %>  
  </div>
</div>