config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  resources :wikis

  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'modify_privacy' => 'wikis#modify_privacy'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :amount_to_be_charged

  def new
    @stripe_btn_data = {
      key: "#{Rails.configuration.stripe[:publishable_key]}",
      description: "BigMoney Membership - #{current_user.name}",
      amount: @amount
    }
  end

  def create

    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the same as user.id. Stripe generates this
      amount: @amount,
      description: "BigMoney Membership - #{current_user.email}",
      currency: "usd"
    )

    flash[:notice] = "Thanks for all the money, #{current_user.name}! Feel free to pay me again."
    current_user.update_attribute(:role, "premium")
    redirect_to root_path

    # Stripe will send back CardErrors, with friendly messages, when something goes wrong.
    # This rescue block catches and displays those errors
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def downgrade
    current_user.update_attribute(:role, "standard")
    flash[:notice] = "Your account has been downgraded."
    redirect_to root_path
  end

  private

    def amount_to_be_charged
      @amount = 14_99
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents/100) 
  end
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <p><strong>You have chosen to upgrade your account to premium. Congratulations! Your recurring monthly payment will be:</strong></p>
    <label class="amount">
      <span><%= pretty_amount(@amount) %></span>
    </label>
  </article>

  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
          data-key="<%= @stripe_btn_data[:key] %>"
          data-amount="<%= @amount %>"
          data-email="<%= current_user.email %>"
          data-description="<%= @stripe_btn_data[:description] %>"
          data-locale="auto">
  </script>
<% end %>