config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:create, :destroy]

  devise_for :users

  resources :wikis

  resources :users, only: [:show, :edit, :update]

  resources :charges, only: [:new, :create]

  get 'downgrade' => 'charges#downgrade'

  get 'modify_privacy' => 'wikis#modify_privacy'

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Franklin" rel="stylesheet">
  </head>

  <body>
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "Wiki Index", wikis_path %></li>
      <% if user_signed_in? %>
        <li class="pull-right"><%= link_to 'Edit Profile', edit_user_registration_path, class: 'navbar-link' %></li>
        <li class="pull-right gravatar"><%= image_tag current_user.avatar_url(48) %></li>
        <li class="pull-right"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'navbar-link' %></li>
        <li class="pull-right"><%= link_to current_user.name, user_path(current_user), class: 'navbar-link' %></li>
      <% else %>
        <li class="pull-right"><%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-link' %></li>
        <li class="pull-right"><%= link_to 'Sign In', new_user_session_path, class: 'navbar-link' %></li>
      <% end %>
    </ul>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>